#!/bin/bash

set -e

# Configuration
RESOURCE_GROUP_NAME="aiad"
LOCATION="eastus2"  # Default region with GPT-5.5 availability (see deploy/main.bicep for the allowed list)
NAME_PREFIX="aiad"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}🚀 AI Audio Descriptions - Automated Azure Setup${NC}"
echo -e "${BLUE}====================================================${NC}"
echo

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo -e "${RED}❌ Azure CLI is not installed. Please install it first:${NC}"
    echo "https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Ensure user is authenticated to Azure
if ! az account show &> /dev/null; then
    echo -e "${RED}❌ You are not logged in to Azure. Please run 'az login' first.${NC}"
    exit 1
fi

# Get subscription info
SUBSCRIPTION_ID=$(az account show --query "id" -o tsv)
SUBSCRIPTION_NAME=$(az account show --query "name" -o tsv)
echo -e "${GREEN}✅ Logged in to Azure${NC}"
echo -e "   Subscription: ${SUBSCRIPTION_NAME} (${SUBSCRIPTION_ID})"
echo

# Confirm deployment to avoid accidental resource creation
echo -e "${YELLOW}⚠️  This script will create the following resources in your Azure subscription:${NC}"
echo "   • Resource Group: ${RESOURCE_GROUP_NAME}"
echo "   • Location: ${LOCATION}"
echo "   • AI Services resource (with GPT-5.5 model deployment)"
echo "   • Storage Account (with audio-description container and CORS)"
echo
read -p "Do you want to continue? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${YELLOW}❌ Setup cancelled.${NC}"
    exit 1
fi

echo -e "${BLUE}📦 Creating Azure resources...${NC}"
echo

# Create resource group if it doesn't exist
echo -e "${YELLOW}Creating resource group...${NC}"
if az group show --name "$RESOURCE_GROUP_NAME" &> /dev/null; then
    echo -e "${GREEN}✅ Resource group already exists: ${RESOURCE_GROUP_NAME}${NC}"
else
    az group create --name "$RESOURCE_GROUP_NAME" --location "$LOCATION"
    echo -e "${GREEN}✅ Created resource group: ${RESOURCE_GROUP_NAME}${NC}"
fi

# Deploy infrastructure using Bicep template
echo -e "${YELLOW}Deploying Azure resources (this may take 5-10 minutes)...${NC}"
DEPLOYMENT_OUTPUT=$(az deployment group create \
    --resource-group "$RESOURCE_GROUP_NAME" \
    --template-file "./deploy/main.bicep" \
    --parameters resourceGroupName="$RESOURCE_GROUP_NAME" location="$LOCATION" namePrefix="$NAME_PREFIX" \
    --query "properties.outputs" \
    --output json)

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Failed to deploy Azure resources.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Azure resources deployed successfully!${NC}"

# Extract resource information from deployment outputs
AI_SERVICES_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.aiServicesName.value')
AI_SERVICES_REGION=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.aiServicesRegion.value')
STORAGE_ACCOUNT_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.storageAccountName.value')
GPT_DEPLOYMENT_NAME=$(echo "$DEPLOYMENT_OUTPUT" | jq -r '.gptDeploymentName.value')

# Retrieve access keys for configuration
echo -e "${YELLOW}Retrieving access keys...${NC}"
AI_SERVICES_KEY=$(az cognitiveservices account keys list --name "$AI_SERVICES_NAME" --resource-group "$RESOURCE_GROUP_NAME" --query "key1" --output tsv)
STORAGE_ACCOUNT_KEY=$(az storage account keys list --account-name "$STORAGE_ACCOUNT_NAME" --resource-group "$RESOURCE_GROUP_NAME" --query "[0].value" --output tsv)

# Generate SAS token with minimal required permissions for 1 year
echo -e "${YELLOW}Generating SAS token...${NC}"
EXPIRY_DATE=$(date -u -d "1 year" '+%Y-%m-%dT%H:%MZ')
SAS_TOKEN=$(az storage container generate-sas \
    --account-name "$STORAGE_ACCOUNT_NAME" \
    --account-key "$STORAGE_ACCOUNT_KEY" \
    --name "audio-description" \
    --permissions acdlrw \
    --expiry "$EXPIRY_DATE" \
    --output tsv)

echo -e "${GREEN}✅ SAS token generated${NC}"

# Create environment configuration file
echo -e "${YELLOW}Creating .env file...${NC}"
cat > .env << EOF
# AI Audio Descriptions Environment Configuration
# Generated by automated setup script on $(date)

VITE_AI_SERVICES_RESOURCE=${AI_SERVICES_NAME}
VITE_AI_SERVICES_KEY=${AI_SERVICES_KEY}
VITE_AI_SERVICES_REGION=${AI_SERVICES_REGION}
VITE_STORAGE_ACCOUNT=${STORAGE_ACCOUNT_NAME}
VITE_BLOB_SAS_TOKEN=${SAS_TOKEN}
VITE_GPT_DEPLOYMENT=${GPT_DEPLOYMENT_NAME}
EOF

echo -e "${GREEN}✅ Created .env file with all configuration${NC}"
echo

# Display summary
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo -e "${GREEN}==================${NC}"
echo
echo -e "${BLUE}📋 Summary of created resources:${NC}"
echo "   • Resource Group: ${RESOURCE_GROUP_NAME}"
echo "   • AI Services: ${AI_SERVICES_NAME}"
echo "   • GPT Deployment: ${GPT_DEPLOYMENT_NAME}"
echo "   • Storage Account: ${STORAGE_ACCOUNT_NAME}"
echo "   • Container: audio-description (with CORS enabled)"
echo
echo -e "${BLUE}🏃‍♂️ Next steps:${NC}"
echo "   1. Run: npm install"
echo "   2. Run: npm run dev"
echo "   3. Open: http://localhost:5173"
echo
echo -e "${GREEN}✨ You're ready to go! Enjoy using AI Audio Descriptions!${NC}"